### ISSUE TITLE
Super Mario World 2: Yoshi's Island (SNES)

### ISSUE THREAD

**Issue by meleu** [meleu/RetroArch-problematic-cheevos#10]
@leiradel

The user @ivestmt666 reported on [RA forum](http://retroachievements.org/viewtopic.php?t=3020&c=19525) and I confirmed here: RetroArch doesn't load the achievements list for "Super Mario World 2: Yoshi's Island (SNES)"

I think there's a problem with the hash calculation for this game in RetroArch and RetroAchievements doesn't return the correct game id ([558](http://retroachievements.org/Game/558)). I tested the same ROM with RASnes9x and the achievements list loads fine.

```txt
RetroArch [libretro INFO] :: "YOSHI'S ISLAND" [checksum ok] LoROM, 16Mbits, ROM+RAM+BAT+Super FX, NTSC, SRAM:256Kbits, ID:YI  , CRC32:D138F224
RetroArch [INFO] :: Environ GET_VARIABLE snes9x_next_overclock:
RetroArch [INFO] ::     Disabled(10MHz)
RetroArch [INFO] :: Environ SET_MEMORY_MAPS.
RetroArch [INFO] ::    ndx flags  ptr              offset   start    select   disconn  len      addrspace
RetroArch [INFO] :: CHEEVOS system RAM: 0x7f9f42c9d010 131072
RetroArch [INFO] :: CHEEVOS save RAM:   0x7f9f42ad7010 32768
RetroArch [INFO] :: CHEEVOS video RAM:  0x1f48fa0 65536
RetroArch [INFO] :: CHEEVOS RTC:        0x7f9f38006d10 0
RetroArch [INFO] :: CHEEVOS testing SNES (8Mb padding).
RetroArch [INFO] :: CHEEVOS getting game id for hash 61233ff18de9bd702417e6ec5175827b
RetroArch [INFO] :: CHEEVOS got game id 0.
RetroArch [INFO] :: CHEEVOS testing NES (discards VROM).
RetroArch [INFO] :: CHEEVOS testing Generic (plain content).
RetroArch [INFO] :: CHEEVOS getting game id for hash cb472164c5a71ccd3739963390ec6a50
RetroArch [INFO] :: CHEEVOS got game id 0.
RetroArch [INFO] :: CHEEVOS this game doesn't feature achievements.
```

Please, tell me if you need more info.

**Comment by leiradel** [comment]
Thanks for the additional info. Could you sniff the network and see which hash RASnes is sending to retrochievements.org?

**Comment by meleu** [comment]
Here is the sniffed request:
```txt
POST /requestgameid.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Retro Achievements Client RASnes9X 0.015
Host: retroachievements.org
Content-Length: 42
Connection: Keep-Alive

u=meleu&m=b2d24aced8d26b584d5903556aa8d32b
```

**Comment by leiradel** [comment]
Hm, I think I'll need to implement this stuff: https://github.com/RetroAchievements/RASuite/blob/a87594e555b75d302104b938424501b1706db11a/RASnes9x/memmap.cpp#L1559

**Comment by leiradel** [comment]
On the other hand, I believe it's possible to have more than one hash per game in Retro Achievements, in which case adding the hash calculated by the generic method in RetroArch would be preferable.

**Comment by leiradel** [comment]
I ended up just adding the plain MD5 hash of the ROM to the Retro Achievements database: cb472164c5a71ccd3739963390ec6a50

This issue can be closed.

**Comment by meleu** [comment]
Yeah! It's working. But how can you add a hash to the RetroAchievements database?

**Comment by leiradel** [comment]
There's an Retro Achievements webservice which allows for adding new MD5 hashes to existing games. Scott sent it to me an year ago, saying that it should be ok to add the plain hashes to the database, but since it would be a huge amount of work to do it for every game, I focused in calculating the hash just like the RA emulators do.

If we start to see many roms being unidentified, I will probably implement that code in `memmap.cpp`.

**Comment by meleu** [comment]
I think somebody did it for all those Contra versions we talked about on that RetroArch issue.
