### ISSUE TITLE
Super Mario World Bros (SNES)

### ISSUE THREAD

**Issue by grenade44** [meleu/RetroArch-problematic-cheevos#13]
This was first mentioned on the retroachievements forum by ivesmt666
This game loads but doesnt register on my profile.
http://retroachievements.org/Game/8811 (link in comments)

Same issue as #12

**Comment by meleu** [comment]
Can you provide the retroarch log, just like you did in #12 .

No need to paste here the full log, you can do this:

```
grep CHEEVOS logfile.log
```

Thanks.

**Comment by grenade44** [comment]
I checked this at the same time as wario adventure and it doesn't load the achievement list. I can provide a log in about 10hrs when I home again.

**Comment by grenade44** [comment]
@meleu sorry later than said but heres the log

RetroArch [INFO] :: CHEEVOS system RAM: 0xb5bad008 131072
RetroArch [INFO] :: CHEEVOS save RAM:   0xb5b8c008 2048
RetroArch [INFO] :: CHEEVOS video RAM:  0xba7f48 65536
RetroArch [INFO] :: CHEEVOS RTC:        0xb5d84a00 0
RetroArch [INFO] :: CHEEVOS testing SNES (8Mb padding).
RetroArch [INFO] :: CHEEVOS getting game id for hash 7c75f7f23ed3fc4ceb43281aa00eadcf
RetroArch [ERROR] :: CHEEVOS error during HTTP GET: timeout.
RetroArch [ERROR] :: CHEEVOS error getting game_id.
RetroArch [INFO] :: CHEEVOS testing NES (discards VROM).
RetroArch [INFO] :: CHEEVOS testing Generic (plain content).
RetroArch [INFO] :: CHEEVOS getting game id for hash ae485c1757a29b95050bdc50532adf57
RetroArch [INFO] :: CHEEVOS got game id 0.
RetroArch [INFO] :: CHEEVOS this game doesn't feature achievements.


let me know if there is anything missing?

**Comment by meleu** [comment]
Somebody solved it. Look my log:
```
RetroArch [INFO] :: CHEEVOS testing Generic (plain content).
RetroArch [INFO] :: CHEEVOS getting game id for hash ba0faa09ccc56c001cfe84a2a885c811
RetroArch [INFO] :: CHEEVOS got game id 8811.
RetroArch [INFO] :: CHEEVOS got achievements for game id 8811.
```

:-)

**Comment by grenade44** [comment]
Ok cool, will test later. When I get a chance

**Comment by meleu** [comment]
I confirmed with a screenshot also:
![captura de tela de 2017-06-01 05 05 02](https://cloud.githubusercontent.com/assets/8508804/26675575/de77496e-469a-11e7-975c-197f5320d52f.png)

**Comment by grenade44** [comment]
Lol, thanks. I will try this hack tonight if I get a chance lol

**Comment by grenade44** [comment]
That's strangle, the list doesn't load for me.

**Comment by meleu** [comment]
I've just noticed that the hash in your log doesn't match mine. I downloaded the ROM from a link in comments.

**Comment by grenade44** [comment]
I redowned from the link and now it works, not sure what happened, that's were I got the rom from originally. Now it works for me :)
