### ISSUE TITLE
Final Fantasy-NES

### ISSUE THREAD

**Issue by chewvodka** [meleu/RetroArch-problematic-cheevos#16]
Game - http://retroachievements.org/Game/1449
Cheevo - http://retroachievements.org/Achievement/3568

This is the first achievement you would unlock when playing the game.  "Win your first victory".  I've created a savestate right before you press the 'A' button to select the enemy to attack.  It does the attack, battle is over.  Cheevo should pop right after you return back to the map screen.  It was broken before, then fixed, and now no longer works again.  I've updated both RetroArch and QuickNES to their latest sources (as of last night).

RetroArch - Build date: Jan 23 2017 / Git version: 7b533c6
QuickNES - 1.0-WIP b9c48e6

I'm not sure if this gets through, as I'm not real good with Github yet.  I created a fork and uploaded the savestate to my own hub, which then established a link to THIS hub as a Pull Request.  That's probably not the way to do it, so I'm trying again by creating a new issue, and adding an attachment to this post.  Hope it gets through so you guys can fix it!

**Comment by chewvodka** [comment]
http://s000.tinyupload.com/download.php?file_id=28872671044774510135&t=2887267104477451013580688

**Comment by meleu** [comment]
Thanks man! I'm really really busy currently, but I'll try to take a look at it when I have time.

Cheers!

**Comment by chewvodka** [comment]
Thanks, I didn't even know if this got in the right place or not.  Hope a fix is found.. really kinda surprised it's not working again.  I hadn't updated my RetroArch/QuickNES until AFTER the other one didn't pop.  For all I know, everything was working right with the version I had and the problem was with the server instead.  But now that I HAVE updated, this first achievement isn't working either, so it re-opens the issue with the latest version.

**Comment by grenade44** [comment]
I'm having issues logging in with any game on try playing, anyone else having issues?

**Comment by chewvodka** [comment]
The last couple of days I've been just trying to access the website to check things like new achievements to play for, and to reset my Final Fantasy cheeves.  The website has gone down almost every night for me, and taking forever to load when it's up.  I think this might be giving "false positives" with games not registering cheeves that should be working otherwise.  Until the site becomes stable again, I've moved on to something else.  I don't want to risk missing further achievements because of the site being down.  -- I would be awesome if there could be a backup mirror site that RetroArch could connect to, or maybe have all the cheeves stored in a database that RetroArch can just download as an asset and allow "offline" unlocks (then it just updates your "online" profile whenever it's connected).

**Comment by grenade44** [comment]
The site seems to be working today and managed to get my missing crash achievements, apparently retroachievements hard drive is full and this is causing the issues with the site.  If I remember correctly I saw leiradel saying something about storing achievements in game until it can connect to the server but that wad a long time again. Maybe some kind of fix could help us out with these issues.

**Comment by chewvodka** [comment]
Any success with this?  I think it's still related to that bug when a game has a battery inside for saving.

**Comment by chewvodka** [comment]
Just thought I'd post up a quick update.  I updated RetroArch today (RetroPie via source) and along with it Quicknes (via source).  I then tried loading my savestate, and the achievement "VICTORY" popped!  So maybe the issue was resolved with either a RetroArch or Quicknes update.  Of course, using a savestate means you're not "HARDCORE" so I'm testing the game now in that mode to see if it still works.

Aaaaannnd... nope!  Argh!

RetroArch 1.4.1
Build Date Feb 15 2017
Git version d8e38be
QuickNES 1.0-WIP f7238df

**Comment by chewvodka** [comment]
Well, I started all over again in HARDCORE mode, and it didn't pop.  Then I completely backed out and reset, then tried again in HARDCORE.  Still nothing.  Then just for kicks I decided to try and load the savestate again just to see it pop.  And it DIDN'T!!  So now something is REALLY messed up.  Might this still be an issue with the achievement/core, or is it maybe the server glitching again?  I mean, it worked just 10 minutes ago, then after I reset my scores on RA then tried it again now it's now.  Are there 2 different servers?  Like one for the website, and one for the "watching"?  Maybe the "watching" server is failing?

**Comment by meleu** [comment]
> Are there 2 different servers? Like one for the website, and one for the "watching"? Maybe the "watching" server is failing?

I'm not sure about the network tricks they use, but the URL is the same for website and for user cheevos database.

Sorry for not being able to investigate it with you. Quite busy on other stuff...

**Comment by meleu** [comment]
@chewvodka sorry for the late reply. But I used the state you [linked above](http://s000.tinyupload.com/download.php?file_id=28872671044774510135&t=2887267104477451013580688) and the cheevo popped as expected.

I'm closing this issue, but if you retest and realize that it's still happening, feel free to reopen.

Thanks!
