### ISSUE TITLE
Master System Achievements

### ISSUE THREAD

**Issue by grenade44** [meleu/RetroArch-problematic-cheevos#18]
@meleu @leiradel

Retroachievements has just started supporting Master System achievements by a custom hacked emulator. Which can be found [here](http://retroachievements.org/viewtopic.php?t=4436&c=22074). Its using a hacked Meka emulator.

I know the meka emulator isn’t available for RetroArch but PicoDrive does play MS games and when I load 1 of the 2 current games it detects them as Megadrive games. I loaded the same rom in the new Meka emulator and it detects the right roms and displays the right achievements.
You can see from [my profile](http://retroachievements.org/user/Grenade44).

[Sonic The Hedgehog (Master System)](http://retroachievements.org/Game/9962)
[Wonder Boy III - The Dragons Trap (Master System)](http://retroachievements.org/Game/10007)

I was wondering if you could take a look and see if you could get a fix for this or do we need a new emulator for MS achievements. Whenever you have a spare moment, that would be great.

This has also shown up, I think N64 support might be coming very soon.
[Super Mario 64 (Nintendo 64)](retroachievements.org/Game/10003)

Thanks
Mike

**Comment by GameDragon2k** [comment]
I can say for sure N64 isn't coming quite soon. That was just a preliminary test. 

Still a bunch of memory issues.

**Comment by grenade44** [comment]
Ok, it's just nice to see new features coming to Retroachievements. I still have my n64 so I can wait lol.

Hopefully we can get master system achievements working with RA.

**Comment by meleu** [comment]
I noticed the same thing in this weekend and saved some logs to send to @leiradel . But the kids demanded my attention... :)

Hey @leiradel , below you can see the log snippets. I noticed that they have different hashes (obviously, they are different ROM files), but RetroAchievements database thinks that the Master System version is the MegaDrive one.

**Sonic the Hedgehog (Master System):**
```
RetroArch [INFO] :: CHEEVOS system RAM: 0x7f878e135740 16384
RetroArch [INFO] :: CHEEVOS save RAM:   (nil) 0
RetroArch [INFO] :: CHEEVOS video RAM:  (nil) 0
RetroArch [INFO] :: CHEEVOS RTC:        (nil) 0
RetroArch [INFO] :: CHEEVOS testing Genesis (6Mb padding).
RetroArch [INFO] :: CHEEVOS getting game id for hash c6f716896b789a25f7cb0c7e861188bc
RetroArch [INFO] :: CHEEVOS got game id 1.
RetroArch [INFO] :: CHEEVOS got achievements for game id 1.
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 1 (Ring Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 2 (Newbie Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 5 (Pit Stop).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 9 (That Was Easy).
RetroArch [INFO] :: CHEEVOS deactivated unlocked achievements in softcore mode.
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 1 (Ring Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 2 (Newbie Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 5 (Pit Stop).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 9 (That Was Easy).
RetroArch [INFO] :: CHEEVOS deactivated unlocked achievements in hardcore mode.
RetroArch [INFO] :: CHEEVOS posted playing game 1 activity.
```

**Sonic the Hedgehog (Mega Drive):**
```
RetroArch [INFO] :: CHEEVOS system RAM: 0x7f916d743740 65536
RetroArch [INFO] :: CHEEVOS save RAM:   0xdd6d10 16384
RetroArch [INFO] :: CHEEVOS video RAM:  (nil) 0
RetroArch [INFO] :: CHEEVOS RTC:        (nil) 0
RetroArch [INFO] :: CHEEVOS testing Genesis (6Mb padding).
RetroArch [INFO] :: CHEEVOS getting game id for hash 2e912d4a3164b529bbe82295970169c6
RetroArch [INFO] :: CHEEVOS got game id 1.
RetroArch [INFO] :: CHEEVOS got achievements for game id 1.
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 1 (Ring Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 2 (Newbie Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 5 (Pit Stop).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 9 (That Was Easy).
RetroArch [INFO] :: CHEEVOS deactivated unlocked achievements in softcore mode.
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 1 (Ring Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 2 (Newbie Collector).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 5 (Pit Stop).
RetroArch [INFO] :: CHEEVOS deactivated unlocked cheevo 9 (That Was Easy).
RetroArch [INFO] :: CHEEVOS deactivated unlocked achievements in hardcore mode.
RetroArch [INFO] :: CHEEVOS posted playing game 1 activity.
```

**Comment by leiradel** [comment]
Thanks for the report and for the logs.

Both hashes are being mapped to the game with ID 1, which is obviously wrong. I'll post to the Retro Achievements thread and see if we can clear this up.

**Comment by meleu** [comment]
@leiradel can you post a link to the thread where I can report this kind of problem? The Wonderboy 3 (Master System) has the same problem.

**Comment by leiradel** [comment]
@meleu it's http://retroachievements.org/viewtopic.php?t=4436

**Comment by meleu** [comment]
@GameDragon2k RAchievs developers store in RA database some hashes to a specific games, a game can have several hashes linked to it. Someone mistakenly stored the Master System version of Sonic the Hedgehog as the MegaDrive version. Now whrn ReteoArch sends the MasterSystem Sonic hash, RetroAchievements thinks that the user is playing the MegaDrive Sonic and send the achievement list for this one.

I hipe I was clear. :-)

**Comment by GameDragon2k** [comment]
Ahh, is that all? Alright.

I'll fix that in a sec. Site is under heavy load at the moment.

**Comment by leiradel** [comment]
@GameDragon2k the same thing happens with Wonder Boy III, the SMS hash (ID 10007) is linked to the MD (ID 6959).

**Comment by leiradel** [comment]
@meleu which is the easiest cheevo in Sonic SMS? Even better, do you have a picodrive savegame near a Sonic SMS cheevo?

**Comment by meleu** [comment]
I think it's clear Green Hill Zone. If wait 2 days I can provide you some savestates.

**Comment by leiradel** [comment]
I think I got it. I was able to get Tastes like Neon (Complete 1 Special Stage) and Welcome to South Island (Complete Green Hill Zone) at the right times.

I'll submit a PR to the picodrive core.

**Comment by leiradel** [comment]
@meleu I've just submitted a PR. If you want to try it before the PR is accepted, get my repo here: https://github.com/leiradel/picodrive

**Comment by leiradel** [comment]
It's in.

**Comment by GameDragon2k** [comment]
@leiradel Should be fixed now.

**Comment by meleu** [comment]
@leiradel you rule!

Will do intensive tests in in a couple of days!

**Comment by grenade44** [comment]
@leiradel

Thanks alot managed to get the complete green hill zone achievements, I still suck at sonic tho.

**Comment by leiradel** [comment]
@grenade44 @meleu let me know if you find any problems.

@GameDragon2k thanks. I wonder if all SMS games will be identified as MD games though.

**Comment by meleu** [comment]
The spurious cheevos on Sonic don't happen anymore. I also got the Green Hill Zone and Bonus stage cheevos. Everything seems to be fine.

Good news, huh!

**Comment by leiradel** [comment]
Can we close this issue?

@meleu can you update the Wiki, adding Picodrive as the "official" core to use for SMS games with achievements? Thanks!

**Comment by grenade44** [comment]
I think we can, will be testing over the weekend. I can always reopen if I fine an issue, 

Retroachievements also supports sega cd now. I haven't had time to test with picodrive.

**Comment by leiradel** [comment]
@grenade44 is there a Sega CD game with achievements that we can test?

**Comment by meleu** [comment]
@leiradel 
> @meleu can you update the Wiki, adding Picodrive as the "official" core to use for SMS games with achievements?

sure!

Also, I'll update the Nestopia status. Unfortunately it doesn't work with cheevos (maybe I'll fire an issue on its issue tracker).

Closing this issue. @grenade44 Feel free to reopen if you find some problem.

I'm also interested in see Sega CD cheevos. Is there any in retroachievements site?

**Comment by grenade44** [comment]
There's a sonic game but it's there looks like there 3 test achievements 

http://retroachievements.org/Game/10062

**Comment by grenade44** [comment]
Here's a post saying that they support sega cd

http://retroachievements.org/viewtopic.php?t=4436&c=22441

**Comment by meleu** [comment]
Great! Thanks.

I noticed that all 3 cheevos for Sonic CD are the same thing: Collect 100 rings. But I'm glad they are starting to work on it anyway!

**Comment by leiradel** [comment]
Sonic CD is a two-files game: a CUE and a BIN. You have to start the game with the CUE, and it's this file RetroArch will use to calculate the hash.

Maybe the Retro Achievements emulator uses the BIN file to calculate the hash? Or maybe a different method?
