### ISSUE TITLE
Centipede-GBC

### ISSUE THREAD

**Issue by grenade44** [meleu/RetroArch-problematic-cheevos#19]
http://retroachievements.org/Game/4871

I have got issues unlocking "kill it now" achievement. http://retroachievements.org/Achievement/48040

I have played the game on the official emu and it unlocks fine but doesn't on retroarch, I've updated from source and still the same. When I get a chance tomorrow I can upload a save state.

**Comment by grenade44** [comment]
@leiradel

**Comment by leiradel** [comment]
Oh, thanks! Let me know when you have a save.

**Comment by grenade44** [comment]
@leiradel hi, Ive uploaded the save state and created a PR https://github.com/meleu/RetroArch-problematic-cheevos/pull/20

**Comment by meleu** [comment]
I confirm the issue here. I killed 10 spiders and the cheevo didn't pop. I didn't test in the official emulator, thou.

@grenade44 I think you used the same branch you used for the Super Mario Advance and the PR became a little messy. Nevermind, I'll add the savestate to the repo anyway. ;-) Thanks.

**Comment by grenade44** [comment]
@meleu sorry im still new to GitHub.

**Comment by meleu** [comment]
@leiradel maybe it's worth to mention that the [Reach level 10 cheevo](http://retroachievements.org/Achievement/48050) is working fine. The bug is with the spiders. (pun intended) :P

**Comment by leiradel** [comment]
Fala aí :)

Cara, será que saberia me dar um resumo do que está acontecendo no mundo 
Retro Achievements e dos problemas atuais do Retro Arch com o suporte a ele?

Tem tanta coisa acontecendo que estou perdendo o fio da meada:

* Suporte a N64: já tem jogo com cheevos para N64?
* Cheevos problemáticos: lembro de uma issue com relação a isso no Git 
Hub, e alguns relatos nos foruns do Retro Achievements
* MD5 do SNES: esse estou por dentro :)

Ainda estou trabalhando com o Game Dragon num frontend para 
desenvolvedores de cheevos que funciona com cores libretro, o que poderá 
trazer cheevos para todas as plataformas suportadas pelo libretro :) 
Isso sem contar outros projetos...

E obrigado pela ajuda, sem você acho que o suporte a cheevos no 
RetroArch já estaria ficando obsoleto novamente.

Sds.,

André

**Comment by meleu** [comment]
@leiradel I think your intention was to send a PM to my email. :rofl: 
I'll answer you via email. :wink:

**Comment by meleu** [comment]
Played Centipede recently and it still have this issue.

https://github.com/meleu/RetroArch-problematic-cheevos/tree/master/Centipede-GBC

**Comment by leiradel** [comment]
Thanks for the report, this cheevo was using addresses in the Echo RAM, so I've patched them to be inside the Work RAM bounds.

**Comment by leiradel** [comment]
Fixed in https://github.com/libretro/RetroArch/pull/5158

**Comment by meleu** [comment]
Yeah! It's working now! Thanks @leiradel ! And thanks @grenade44 for the original report!

Closing the issue.

**Comment by grenade44** [comment]
Thanks again @leiradel, will update when I'm home.
