### ISSUE TITLE
Tetris - NES

### ISSUE THREAD

**Issue by chashodges** [meleu/RetroArch-problematic-cheevos#26]
http://retroachievements.org/Achievement/11322

This achievement does not seem to work for me in Retroarch. I have tried all compatible NES cores with not luck, as well as testing various ROM dumps. All other achievements have unlocked without issues using FCE and the (!) dump. 

For the 'Shhh' achievement, you have to watch the rolling demo from the title screen, wait until the CPU makes a Tetris (4 lines) about 45 seconds into the demo, and then hit start when the screen is flashing. You then start a new Game B and the screen should flash before awarding you the points from the demo when the first piece starts dropping.

**Comment by meleu** [comment]
There's a comment on that cheevo's page saying: "Works fine in retroarch 1.6 with fceumm". Maybe you're not doing the right thing. The cheevo looks like a riddle...

**Comment by chashodges** [comment]
I've tried multiple times and that method was corroborated by others. I did reach out to that user a while back but didn't get a response.

**Comment by chashodges** [comment]
Tried again this morning - managed to get it by loading Game A after the demo trick not Game B. Sorry!

Please mark this issue as solved / closed.

**Comment by meleu** [comment]
Thanks for verifying that! :-)
