### ISSUE TITLE
Donkey Kong NES - IT'S A MEE

### ISSUE THREAD

**Issue by SuperMeatBro** [meleu/RetroArch-problematic-cheevos#27]
http://retroachievements.org/Achievement/3394 That achievement doesnt trigger on Retroarch with Fceumm and Nestopia core (last revisions)
it triggered at 20 000 points on RaNes like it should.

**Comment by meleu** [comment]
Will try to take a look into it later. But just FYI, RetroAchievements don't work with Nestopia.

**Comment by SuperMeatBro** [comment]
Oh, now i remember why i used Fceumm.

**Comment by meleu** [comment]
I've just got this cheevo on my Android/Retroarch/fceumm:

Closing this issue.
