### ISSUE TITLE
Crystalis (NES) - problems with the level cheevos

### ISSUE THREAD

**Issue by meleu** [meleu/RetroArch-problematic-cheevos#28]
@leiradel 
I've found a problem in [Crystalis (NES)](http://retroachievements.org/Game/1636). I reached the level 2 and the related cheevo didn't pop up ([Ding!](http://retroachievements.org/Achievement/8022)). Playing with fceumm.

I've tested in RANes and the cheevo works fine.

Here is a savestate (saved with RetroArch/fceumm) to let you check (you just have to kill that blue thing and you'll level up): [Crystalis (USA).state.zip](https://github.com/meleu/RetroArch-problematic-cheevos/files/1371754/Crystalis.USA.state.zip)

By the way, there's another user on the game wall saying:

> Hm with QuickNES I'm not able to get the level achievements, makes me a bit sad *sniff*

Please, let me know if you need more info.

**Comment by leiradel** [comment]
Is it too much trouble if I ask you to try with a different core?

**Comment by meleu** [comment]
Not really. You mean QuickNES, right? I only know fceumm, QuickNES and Nestopia, and AFAIK Nestopia doesn't support cheevos.

**Comment by leiradel** [comment]
That's correct.

**Comment by leiradel** [comment]
If you can make a savegame just before the achievement I appreciate. The FCEUmm savegame isn't working.

**Comment by meleu** [comment]
I'll try it soon. I'm at work now but I think I can try it on my PS Vita when things go calmer :-). Probably in an hour or 2. If you are bored and with free time and wanna try it, it's not very hard time consuming:

1. start the game
2. go left and you'll be in a village.
3. go up and enter in the first house, the guy will give you some money ($100).
4. go down to the weapon store and buy a sword.
5. go north, to the forest, out of town and kill 30 enemies (you'll need to go back to the village and immediately go back to the forest some times to make the enemies appear again).
6. after killing 30 enemies you'll  be on level 2.


BTW, I tried to talk to you on the discord server but it seems to be down...

**Comment by meleu** [comment]
@leiradel 
> The FCEUmm savegame isn't working.

Not sure it it's the case, but... The save state I linked above is zipped and you need to unzip it. I did it to attach it in the issue comment. 😅

**Comment by meleu** [comment]
Ooops! My instructions to get the sword were wrong! Sorry, I've edited that post.

Anyway, I'm trying to generate a savestate right now. ;-)

**Comment by meleu** [comment]
@leiradel 
weird... I've just tried to reproduce the issue on Android/RetroArch/fceumm and it worked fine.

The problem I reported in the OP was on PS Vita/RetroArch/fceumm (sorry, I forgot to mention it was on PS Vita). I'll try on this platform again a report back.

**Comment by meleu** [comment]
solved in https://github.com/libretro/RetroArch/pull/5555
