### ISSUE TITLE
Updates for Game Boy Advance cores

### ISSUE THREAD

**Issue by leiradel** [meleu/RetroArch-problematic-cheevos#3]
[vbam-libretro](https://github.com/libretro/vbam-libretro) should be working just fine, it just needs some tests to validate. The [mGBA core](https://github.com/libretro/mgba) should also be working.

[vba-next](https://github.com/libretro/vba-next) doesn't support the memory map interface, so achievements won't work ok with it.

**Comment by meleu** [comment]
Are you talking about Game Boy or Game Boy Advance?

**Comment by leiradel** [comment]
vbam-libretro and vba-next only support GBA. mGBA suports GB, GBC and GBA, but it only supports achievements for GBA games.

**Comment by meleu** [comment]
Thanks, I'm going to update the [core compatibility list](https://github.com/meleu/RetroArch-problematic-cheevos/blob/master/core_compatibility.md).

**Comment by leiradel** [comment]
Please notice that I *believe* mGBA and vbam-libretro are working ok with achievements, I'm not 100% positive.

**Comment by leiradel** [comment]
Maybe mGBA should also appear in the Game Boy/Game Boy Color list, but as not supported?

**Comment by meleu** [comment]
No problem. @grenade44 gave some feedback on that retroachievements.org post, and he is using mgba.
I think @Cabrunco tested some GBA cheevos in mgba too.

> Maybe mGBA should also appear in the Game Boy/Game Boy Color list, but as not supported?

I agree.

**Comment by meleu** [comment]
@leiradel do you have something to say about [vba-next](https://github.com/libretro/vba-next)?

**Comment by leiradel** [comment]
I already did! :)

> vba-next doesn't support the memory map interface, so achievements won't work ok with it.

**Comment by meleu** [comment]
Oh sorry! :sweat_smile: 
I'll put this info in the list.

**Comment by meleu** [comment]
I renamed the title for Game Boy Advance specific
If we have updates for other system, let's open another issue. :wink:

**Comment by chewvodka** [comment]
Will there be cheevo capabilities in mGBA for regular GB/GBC or when you say it only supports GBA that means never?  By default, RetroPie (though you don't necessarily have to use it) runs GB/GBC roms in Gambatte. Is that a compatible core to check on?  It does work as far as pulling the cheevo list..

**Comment by leiradel** [comment]
For now, mGBA will only support GBA achievements. For GB/GBC, I have a fix to Gambatte waiting to be discussed and approved by the libretro team. If you know how to clone and compile a libretro core, you can try the fix directly from my [repository](https://github.com/leiradel/gambatte-libretro).

**Comment by leiradel** [comment]
@meleu I think we can close this issue, as the list has already been updated.
