### ISSUE TITLE
Some broken N64 achievements

### ISSUE THREAD

**Issue by GameDragon2k** [meleu/RetroArch-problematic-cheevos#30]
@meleu suggested I make a new issue for this.  This is somewhat an extension of issue #23 .

As of now, any achievements that uses the flag "Add Source, Sub Source, or Add Hits" do not work on RetroArch. Two notable games that make use of these flags are Star Fox 64 and Pilotwings 64. These flags are currently exclusive to N64. All achievements that do not have these flags work fine to my knowledge.

@leiradel The source code for this can be found [here](https://github.com/GameDragon2k/RASuite/tree/rap64-240). The files you may want to look at is RA_Achievement.cpp/.h and RA_Condition.cpp/.h.

**Comment by leiradel** [comment]
Yeah, I've already compared the implementations and they look equivalent. I'm starting to think there may be something wrong with the parser (see https://github.com/meleu/RetroArch-problematic-cheevos/issues/29).

**Comment by GameDragon2k** [comment]
Add Source implementation seems to be fine now. Once I verify Add Hits is working, I'll close this issue.

**Comment by meleu** [comment]
Really cool! But what changed? Were there any related changes in the core or RetroArch?

**Comment by meleu** [comment]
closing this issue.

@GameDragon2k feel free to reopen if you think it deserves to be opened.
