### ISSUE TITLE
Mortal kombat 2 gameboy 1 problem

### ISSUE THREAD

**Issue by LootusMaximus** [meleu/RetroArch-problematic-cheevos#31]
Before opening an issue, keep in mind that this issue tracker is for reporting **cheevos problems when running in RetroArch AND NO PROBLEMS IN OFFICIAL RetroAchievements EMULATORS**.

In order to make somebody take a look into the issue you're reporting, please assure that the problem **doesn't happen when playing in official emulators**.

Also, you have to detail the steps to reproduce your issue. Post links to the game and the cheevos you're facing problems.

If the needed condition to trigger the issue is time demanding, we also need a savestate to check it.

Thanks for your comprehension and for helping to make RetroArch better. :)

**Comment by LootusMaximus** [comment]
http://retroachievements.org/Achievement/54568 this one doesnt appear to work on retroarch. U can do it easily by starting on easy and crouching in the corner

**Comment by meleu** [comment]
Have you tested it on the official emulator?

**Comment by LootusMaximus** [comment]
No but i talked to dev and a user who got it and it should be working

**Comment by LootusMaximus** [comment]
I only have android or i would

**Comment by LootusMaximus** [comment]
Ill just add one more thing. This is almost like a glitch. They must have not intended for both fighters to end a round with full health. Because it instantly ends the game "game over" and u cant even use a continue. Even its the first round of fight.

**Comment by LootusMaximus** [comment]
Could someone help me confirm this? Its very easy to do. Just start 1st round on easy and back up to edge of screen and duck. They will punch over your head if its easy first fight.

**Comment by LootusMaximus** [comment]
Also im limited to gambatte on android. Even tho site says sameboy should be on android

**Comment by meleu** [comment]
@leiradel I confirm this cheevo isn't working on RetroArch/gambatte.

Here's a savestate: 
[Mortal Kombat II (USA, Europe).state.zip](https://github.com/meleu/RetroArch-problematic-cheevos/files/1518533/Mortal.Kombat.II.USA.Europe.state.zip)

In this state the game is paused. Keep pressing down before unpause the game and wait for the time out. The cheevo should pop after getting the game over.

I checked this cheevo logic and it seems very simple. There's no special flags, not even hit counts...

**Comment by rzumer** [comment]
State does not work for me. Possibly outdated. Please provide a new one for testing if this issue is still valid.

**Comment by LootusMaximus** [comment]
This can be done by starting on easy retreating to corner and ducking. Let the game timer run out. With neither player taking damage. If its first fight and easy. They should never hit you while crouching in corner

**Comment by rzumer** [comment]
Works for me with gambatte in RALR. Probably fixed a while back.

**Comment by meleu** [comment]
closing it as fixed. @LootusMaximus feel free to reopen if the problem still happens with you **when using an uptodate version of the core**.
