### ISSUE TITLE
nonstop cheevos retrying request

### ISSUE THREAD

**Issue by retro-wertz** [meleu/RetroArch-problematic-cheevos#32]
I decided to post this issue here since this can happen because of unusual way of loading rom. the problem is it keeps spamming this:
```
[INFO] [CHEEVOS]: Couldn't connect to server after 5 tries
[INFO] [CHEEVOS]: Retrying HTTP request: 2 of 5
[INFO] [CHEEVOS]: Retrying HTTP request: 3 of 5
[INFO] [CHEEVOS]: Retrying HTTP request: 4 of 5
[INFO] [CHEEVOS]: Retrying HTTP request: 5 of 5
```

how to replicate:
1. find a pc-engine/tg-16 bios name games Express CD.
   crc 51a12d90
2. load this bios in supergrafx(beetle sgx) (its what i am currently using) or pc-engine/pce-cd. extension must be .pce so it can be seen in browser at least.
3. check that  achievements are loaded. it should load achievements for Rondo of Blood for some reasons.
4. Close the core and log should start spamming.

Im not requesting a fix since like what i said, its an unusual way of loading rom. but probably something to look into... and maybe a |hint| so we can probably hook up cheevos for the actual Rondo of Blood CD
thanks.

![screenshot_2017-12-09_08-26-33](https://user-images.githubusercontent.com/23315382/33790387-b83d613c-dcba-11e7-8c4b-1ce8f59f88d0.png)

**Comment by leiradel** [comment]
I believe it's related to the downloading of cheevo badges. If wait long enough, does it eventually stop?

**Comment by retro-wertz** [comment]
no, it does not stop. and this does not seem to be caused alone by loading the bios since it happened while i was loading some hacked burger time - nes game during one of my test (another issue)

**Comment by meleu** [comment]
@retro-wertz I'm trying to cleanup this issue tracker.

I'm closing this issue but could you please try to reproduce the issue in the current version of RetroArch and reopen this issue if the problem persists?

Thanks in advance.

---

By the way, leiradel wasn't talking about loading the BIOS, but loading the **badges**. He was refering to a new feature related to cheevos where, if enabled, makes RetroArch show the badges of each achievement on the Achievement List.
