### ISSUE TITLE
NeoGeo Pocket Color System

### ISSUE THREAD

**Issue by chewvodka** [meleu/RetroArch-problematic-cheevos#34]
Tried playing a game:
https://retroachievements.org/game/11719
I was pleasantly surprised to see it offered cheevos.  However, the system doesn't seem to be working in RetroArch.  This is mentioned in the game's comments, so it's a known issue.  Just putting up the "issue" so there is an official thread starting for it.  :)

**Comment by leiradel** [comment]
It seems it was fixed in RetroArch 1.7.2, could you try and see if it works?

**Comment by chewvodka** [comment]
I'm already on 1.7.3.  The first cheevo should have popped when I got 208 rings..
https://retroachievements.org/Achievement/58303

I just tried again, I'm at 168 and no Cheevo.  I wonder if my core is out of date?  It reads:
1.7.3 - Mednafen NeoPop v0.9.36.1 ab5d1d5

I don't have one now, but I can try to create a savestate for you you it will help.  I just need to remember how.  :)

**Comment by chewvodka** [comment]
Yup looks like that was the cause.  Updated from source.. now have it working.
1.7.3 - Mednafen NeoPop v0.9.36.1 69293c9
