### ISSUE TITLE
SameBoy core issue? - Lucky Luke GBC

### ISSUE THREAD

**Issue by kdecks** [meleu/RetroArch-problematic-cheevos#39]
Using the Sameboy Core for Lucky Luke (GBC) - RA checksum: 7cf3670a8f345344e4789e41503d7da6

Lucky Luke page: http://retroachievements.org/Game/6203

The following achievements trigger on entering the second stage (stagecoach) on hard and in this order: 
http://retroachievements.org/Achievement/31388 - Get a perfect on a bonus
http://retroachievements.org/Achievement/31374 - Finish Level 6
http://retroachievements.org/Achievement/31373 - Finish Level 5 on hard
http://retroachievements.org/Achievement/31372 - Finish Level 5
http://retroachievements.org/Achievement/31371 - Finish Level 4 on hard
http://retroachievements.org/Achievement/31370 - Finish Level 4
http://retroachievements.org/Achievement/31378 - Finish Level 8
http://retroachievements.org/Achievement/31377 - Finish Level 7 on hard
http://retroachievements.org/Achievement/31376 - Finish Level 7
http://retroachievements.org/Achievement/31375 - Finish Level 6 on hard
http://retroachievements.org/Achievement/31381 - Finish Level 9 on hard
http://retroachievements.org/Achievement/31380 - Finish Level 9
http://retroachievements.org/Achievement/31379 - Finish Level 8 on hard
http://retroachievements.org/Achievement/31387 - Finish Level 12 on hard and beat the game
http://retroachievements.org/Achievement/31386 - Finish Level 12 and beat the game
http://retroachievements.org/Achievement/31383 - Finish Level 10 on hard
http://retroachievements.org/Achievement/31384 - Finish Level 11
http://retroachievements.org/Achievement/31382 - Finish Level 10
http://retroachievements.org/Achievement/31385 - Finish Level 11 on hard

I've recreated the issue.
![image](https://user-images.githubusercontent.com/32706333/54897465-2388c800-4e8e-11e9-9cb7-c951e2809b29.png)

**You can recreate the issue using the SameBoy core** and loading the password: Dog, Prospector, Horse, Luke, Horse

Most of these achievements are checking a single, stable value which is the stage id (0x00dfc3). Or the stage id and a difficulty check. The conditions have 0 hits required. I've watched this address in Retroarch using an external memory viewer and it acts as expected. When in the memory the stage id is 0xa SameBoy reads it as at least the following values: 0x19, 0x1e, 0x23, 0x27, 0x31, 0x36, 0x3a (stage id for finishing stages 6 though 12). Interestingly enough does not trigger for stages 1 through 4. (0x00dfc3 == 0x16 and the end of stage 4.)

**Logic tells me that this is an issue with the SameBoy core**, but perhaps I've missed something. Maybe rcheevos will resolve and make this issue irreverent.

**Comment by kdecks** [comment]
I tested Gambette core and RAVba with no issue.

**Comment by kdecks** [comment]
Gambette core doesn't work at all. These achievements are simple so it's something besides the achievement code.

**Comment by rzumer** [comment]
Gambatte side fixed in https://github.com/libretro/gambatte-libretro/pull/124.

**Comment by rzumer** [comment]
Should be fixed soon (see https://github.com/LIJI32/SameBoy/issues/157).

**Comment by meleu** [comment]
closing this as fixed. @kdecks feel free to reopen if the problem still happens with you **when using uptodate versions of the mentioned cores**.
