### ISSUE TITLE
Chronicle of the Radia War | Radia Senki

### ISSUE THREAD

**Issue by televandalist** [meleu/RetroArch-problematic-cheevos#42]
http://retroachievements.org/game/7161

The achievements work as they should while using the FCEUmm core. XashTheStampede sent me a video of several achievements randomly popping with the Mesen core, which I was able to recreate with Mesen, but not FCEUmm. 

I'm not sure what the differences between the cores are, but it might be noteworthy that most useful addresses in that game are in SRAM between 0x006011 and 0x0060ff.

**Comment by Sanaki** [comment]
This needs to be verified, but can likely be closed now.
