### ISSUE TITLE
Mesen core and SRAM

### ISSUE THREAD

**Issue by televandalist** [meleu/RetroArch-problematic-cheevos#44]
Due to how many achievements do not work properly in both Radia Senki and EarthBound Zero using Mesen, I decided to look further into it. It definitely seems tied to SRAM, at least. 

The following games have sets on RA and have code notes within SRAM:
-Chronicle of the Radia War | Radia Senki
-Destiny of an Emperor
-Digital Devil Story: Megami Tensei II
-Downtown Special: Kunio-kun no Jidaigeki da yo Zenin Shugo!
-Dragon Warrior
-Dragon Warrior II
-Dragon Warrior III
-Dragon Warrior IV
-Earthbound Zero
-Final Fantasy
-Final Fantasy II
-Final Fantasy III
-Kirby's Adventure
-Legend of Zelda
-Maniac Mansion
-StarTropics
-Sweet Home
-Zelda II

Several of these games have tickets, some for cheevos that utilize SRAM, some don't. 

These are all tickets opened on 'SRAM cheevos' by users playing with the Mesen core:
https://retroachievements.org/ticketmanager.php?i=16432
https://retroachievements.org/ticketmanager.php?i=16377
https://retroachievements.org/ticketmanager.php?i=16374
https://retroachievements.org/ticketmanager.php?i=16373
https://retroachievements.org/ticketmanager.php?i=16372
https://retroachievements.org/ticketmanager.php?i=15881
https://retroachievements.org/ticketmanager.php?i=18783
https://retroachievements.org/ticketmanager.php?i=18780
https://retroachievements.org/ticketmanager.php?i=18134

And also 'SRAM cheevos' by users playing with 'Unknown' cores/emus:
https://retroachievements.org/ticketmanager.php?i=19316
https://retroachievements.org/ticketmanager.php?i=15466
https://retroachievements.org/ticketmanager.php?i=15465
https://retroachievements.org/ticketmanager.php?i=13791
https://retroachievements.org/ticketmanager.php?i=7848
https://retroachievements.org/ticketmanager.php?i=13121
https://retroachievements.org/ticketmanager.php?i=18840
https://retroachievements.org/ticketmanager.php?i=12920
https://retroachievements.org/ticketmanager.php?i=14739
https://retroachievements.org/ticketmanager.php?i=10188
https://retroachievements.org/ticketmanager.php?i=10107
https://retroachievements.org/ticketmanager.php?i=5481
https://retroachievements.org/ticketmanager.php?i=16826

Oh, and RANes:
https://retroachievements.org/ticketmanager.php?i=19010
https://retroachievements.org/ticketmanager.php?i=12398
https://retroachievements.org/ticketmanager.php?i=18187
https://retroachievements.org/ticketmanager.php?i=15350
https://retroachievements.org/ticketmanager.php?i=15301
https://retroachievements.org/ticketmanager.php?i=15299
https://retroachievements.org/ticketmanager.php?i=13445
https://retroachievements.org/ticketmanager.php?i=13444
https://retroachievements.org/ticketmanager.php?i=17730
https://retroachievements.org/ticketmanager.php?i=14734
https://retroachievements.org/ticketmanager.php?i=18494

Can't forget FCEUmm:
https://retroachievements.org/ticketmanager.php?i=17090

----------------------------------------------------------------------
I did the same thing for GameBoy/GameBoy Color, too. All SRAM related: 

Gambatte
https://retroachievements.org/ticketmanager.php?i=19334
https://retroachievements.org/ticketmanager.php?i=18579
https://retroachievements.org/ticketmanager.php?i=19333
https://retroachievements.org/ticketmanager.php?i=17702
https://retroachievements.org/ticketmanager.php?i=15222
https://retroachievements.org/ticketmanager.php?i=15810
https://retroachievements.org/ticketmanager.php?i=15865
https://retroachievements.org/ticketmanager.php?i=17700
https://retroachievements.org/ticketmanager.php?i=17701
https://retroachievements.org/ticketmanager.php?i=17307
https://retroachievements.org/ticketmanager.php?i=10692
https://retroachievements.org/ticketmanager.php?i=16756
https://retroachievements.org/ticketmanager.php?i=17258

Unknown
https://retroachievements.org/ticketmanager.php?i=18125
https://retroachievements.org/ticketmanager.php?i=16084
https://retroachievements.org/ticketmanager.php?i=13015
https://retroachievements.org/ticketmanager.php?i=9585
https://retroachievements.org/ticketmanager.php?i=10859
https://retroachievements.org/ticketmanager.php?i=7007
https://retroachievements.org/ticketmanager.php?i=6999
https://retroachievements.org/ticketmanager.php?i=7000
https://retroachievements.org/ticketmanager.php?i=7001
https://retroachievements.org/ticketmanager.php?i=7002
https://retroachievements.org/ticketmanager.php?i=7003
https://retroachievements.org/ticketmanager.php?i=7004
https://retroachievements.org/ticketmanager.php?i=7005
https://retroachievements.org/ticketmanager.php?i=7006
https://retroachievements.org/ticketmanager.php?i=1122
https://retroachievements.org/ticketmanager.php?i=19324
https://retroachievements.org/ticketmanager.php?i=15704
https://retroachievements.org/ticketmanager.php?i=12355
https://retroachievements.org/ticketmanager.php?i=8404
https://retroachievements.org/ticketmanager.php?i=8166
https://retroachievements.org/ticketmanager.php?i=4843
https://retroachievements.org/ticketmanager.php?i=3826
https://retroachievements.org/ticketmanager.php?i=3398
https://retroachievements.org/ticketmanager.php?i=3283
https://retroachievements.org/ticketmanager.php?i=2093
https://retroachievements.org/ticketmanager.php?i=8231
https://retroachievements.org/ticketmanager.php?i=8233
https://retroachievements.org/ticketmanager.php?i=8234
https://retroachievements.org/ticketmanager.php?i=9575
https://retroachievements.org/ticketmanager.php?i=18932
https://retroachievements.org/ticketmanager.php?i=18479
https://retroachievements.org/ticketmanager.php?i=18930
https://retroachievements.org/ticketmanager.php?i=18931
https://retroachievements.org/ticketmanager.php?i=11679
https://retroachievements.org/ticketmanager.php?i=16528
https://retroachievements.org/ticketmanager.php?i=16048

RAVBA
https://retroachievements.org/ticketmanager.php?i=14609
https://retroachievements.org/ticketmanager.php?i=17476
https://retroachievements.org/ticketmanager.php?i=18991
https://retroachievements.org/ticketmanager.php?i=14275
https://retroachievements.org/ticketmanager.php?i=16051
https://retroachievements.org/ticketmanager.php?i=14222

SameBoy
https://retroachievements.org/ticketmanager.php?i=17271

**Comment by rzumer** [comment]
I tested [this one](https://retroachievements.org/ticketmanager.php?i=16377) and could not reproduce the issue. Considering all the reports for this title are from the same person I am not convinced that the issue exists to this day, and if we want to have any hope of fixing it a reliable sample is needed anyway (e.g. save state before a trigger that should unlock but does not).

**Comment by rzumer** [comment]
This is more easily reproducible with https://github.com/meleu/RetroArch-problematic-cheevos/issues/42.

**Comment by Sanaki** [comment]
The relevant issue, for reference: SourMesen/Mesen#642

**Comment by Sanaki** [comment]
This can be closed now.
