### ISSUE TITLE
Kirby Super Star - SNES

### ISSUE THREAD

**Issue by meleu** [meleu/RetroArch-problematic-cheevos#6]
@leiradel let's try to talk here. :-)

I tried your recent [RetroArch commit](https://github.com/leiradel/RetroArch/commit/2b345b8d48148eec139d67e535a4467db06c267a) with Snes9x 2010 (former Snes9x Next) and the [Hungriest Runner](http://retroachievements.org/Achievement/24594) still doesn't work.

I'm compiling the other libretro SNES cores to test.

@GameDragon2k can you confirm if it works with RASNES?

**Comment by leiradel** [comment]
It won't work on SNES9x 2010, this core isn't implementing the memory map interface. Please try with SNES9x Next.

SNES9x 2010 is listed as the core with the best compatibility, I believe this is an error. I think the best core to unlock cheevos is SNES9x Next.

**Comment by leiradel** [comment]
Hm, I've changed the way I calculate bit values and I could get Hungriest Runner with SNES9x 2010. This core doesn't implement the memory map interface, but it does implement the get_memory_* API. This API is far inferior to the memory map, and some cheevos may not work with it.

If someone wants to give it a try, the commit is this one: https://github.com/leiradel/RetroArch/commit/170c98b59393bac40a410cf25fc69a2053066c7b

**Comment by meleu** [comment]
Let's use links to the core repositories. When I say Snes9x 2010 I'm talking about this one:
https://github.com/libretro/snes9x2010

The description says "Snes9x 2010. Port of Snes9x 1.52+ to Libretro (previously called SNES9x Next). Rewritten in C and several optimizations and speedhacks."

Can you post a link to the snes9x next repo?

**Comment by leiradel** [comment]
Some additional tests with other cheevos that were fixed recently would be awesome to avoid regressions.

**Comment by meleu** [comment]
I'll test this night ;-)

**Comment by leiradel** [comment]
SNES9x Next is this one: https://github.com/libretro/snes9x

**Comment by meleu** [comment]
Tested here.
[Snex9x 2010](https://github.com/libretro/snes9x) is working and [Snex9x](https://github.com/libretro/snes9x) isn't.
I got Hungriest Runner with Snes9x 2010 (what I think is the former snes9x next), and then did a reset in this cheevo and tried with Snes9x. It didn't work.

@leiradel can you confirm with your libretro fellows what is the actual "snex9x next"?

**Comment by leiradel** [comment]
It's this one: https://github.com/libretro/snes9x

**Comment by meleu** [comment]
Well... The snes9x from this repository (https://github.com/libretro/snes9x) isn't working.

And tested Hungriest Runner again with [bsnes](https://github.com/libretro/bsnes-libretro) too. It's working fine! :-)

**Comment by meleu** [comment]
@leiradel according [to this answer](https://github.com/libretro/RetroArch/pull/3992#issuecomment-260227771) the [Snes9x 2010](https://github.com/libretro/snes9x2010) description seems to be correct. It really is the actual Snes9x next.

**Comment by grenade44** [comment]
I cant currently test but this emulator used to work with snes achievements. https://github.com/RetroPie/ARMSNES-libretro

**Comment by GameDragon2k** [comment]
@meleu @leiradel Can confirm both Hungriest Runner and Speed Eater are working now.

**Comment by meleu** [comment]
Solved, then I'm closing this issue.
