### ISSUE TITLE
Final Fantasy (NES) - FCEUmm

### ISSUE THREAD

**Issue by chewvodka** [meleu/RetroArch-problematic-cheevos#7]
http://retroachievements.org/Achievement/3568
Win your first battle.

Works fine in QuickNES.  Attached save state happens right after I click the monster to fight with my last player.  The animation happens for the attack, kills the monster, and the fight is over.  In QuickNES the cheevo pops right after returning to the map (after all the awards are given).
[tmp_22206-Final Fantasy (USA).state-1749848042.zip](https://github.com/meleu/RetroArch-problematic-cheevos/files/588277/tmp_22206-Final.Fantasy.USA.state-1749848042.zip)

**Comment by chewvodka** [comment]
I'm still new with Github, should I have put this on the "code" page?  I don't know how to do that.

**Comment by GameDragon2k** [comment]
It's okay. Although, QuickNES is currently the main NES core for achievements, so if it's working on that, there's no issue.

If possible, you should use QuickNES core for all your tests until FCEUmm core is properly supported.

**Comment by meleu** [comment]
@chewvodka , the @GameDragon2k is right. The tests should be made in QuickNES.

But thanks for your save. It can be useful if somebody wants to fix the FCEUmm cheevo issue. And don't worry about the github details to help us here. The way you did is fine. :-)

What core did you use to make this save state?

**Comment by chewvodka** [comment]
I used FCEUmm (in the title lol).  I'll continue reporting as I play, but I'll switch over to QuickNES for the time being.

**Comment by meleu** [comment]
Yo buddy. I opened an issue on libretro-fceumm repository talking about this issue:
https://github.com/libretro/libretro-fceumm/issues/52

I'm closing this here.

Thanks!
