### ISSUE TITLE
Crash-Bandicoot-2-N-Tranced-GBA

### ISSUE THREAD

**Issue by grenade44** [meleu/RetroArch-problematic-cheevos#8]
This crash game still unlocks achievement's when loading the game. I'm using mGBA.

**Comment by meleu** [comment]
It doesn't happen here.
I'm using the most recent RetroArch and mGBA.
You can see in my [RA Homepage](http://retroachievements.org/user/meleu) that I "played" (actually I just started the game and exited) and I don't have any cheevo.

While in mGBA I checked the Achievement List and everything is fine. All the cheevos are Locked.

Can you give details about your system?

**Comment by meleu** [comment]
Just to make it clear, we are talking about this game: http://retroachievements.org/Game/5535
Right?

**Comment by meleu** [comment]
And to make sure that it's recording the cheevos I finished the tutorial (first stage) and earned the [Thoroughtorial](http://retroachievements.org/Achievement/30405).

Then I'm considering this game as having no issues. Is it OK for you?

**Comment by GameDragon2k** [comment]
Can confirm it's working for me too.

@grenade44, if you're still having issues. Make sure you're using the latest version of RetroArch and mGBA.

**Comment by grenade44** [comment]
I will take another look, my retroarch is only couple of days out of date. I will rebuild from source and update my mGBA, I wonder if I'm using the wrong rom. Let me do some checks.

**Comment by grenade44** [comment]
@meleu @GameDragon2k what rom did you use? I updated mGBA and changed to the U rom as it mentioned on retroachievements and completed the first level and no achievement. Updating retroarch now

**Comment by grenade44** [comment]
I know this for achievements but does anyone know why it's not as omg my progress?

**Comment by GameDragon2k** [comment]
@grenade44 Hmm you're right. It doesn't save on mGBA at all for some reason.

I did get it to work on VBA-M however. Saving seems fine there. Haven't run into achievement issues with that either. Using (U) rom.

**Comment by meleu** [comment]
@GameDragon2k Please sorry my ignorance, but what do you mean "save" in this context?
Do you mean save as in the original Game Boy Advance hardware?
I'm asking because I'm playing "Castlevania - Aria of Sorrow" using mGBA (on my Linux Mint/x86 and RetroPie/raspi2), and it's saving correctly.

**Comment by grenade44** [comment]
Yes within Gameboy hardware, when I get a sec I will try and play the game on another emulator.

**Comment by GameDragon2k** [comment]
@meleu Internal saves are working for other games I've tried on mGBA, but not this game.
Works on VBA-M.

**Comment by meleu** [comment]
It's weird. If you guys want someone taking a look at it, open an issue on mgba issue tracker:
https://github.com/libretro/mgba/issues

I'm closing this issue here because I'm getting this game working fine with the cheevos, OK?
(If you find another cheevos issue with this game we can reopen it)

Cheers!
