### ISSUE TITLE
Arkanoid: Doh it Again (SNES)

### ISSUE THREAD

**Issue by meleu** [meleu/RetroArch-problematic-cheevos#9]
This issue is unrelated with earning achievements itself, but with RetroArch ~~(or Snes9x2010 ?)~~.

The user GapporinRA reported [on RA forum](http://retroachievements.org/viewtopic.php?t=3020) that **RetroArch (up to date) crashes when loading "Arkanoid: Doh it Again" on Snes9x2010 with cheevos enabled. If the cheevos feature is disabled the ROM loads fine.**

I reproduced it on my Android phone and can confirm (crashes with cheevos enabled, runs fine with cheevos disabled). When I get home I'll try on my Linux box and get more info to help the diagnosis.

@leiradel , reporting here is enough? If not, should we report it to RetroArch ~~or Snes9x2010~~?

**Comment by leiradel** [comment]
It's ok to report here. I'll take a look.

Is it a real crash or RetroArch freezes? I'm asking because I've just fixed an issue where it was freezing under certain circumstances.

**Comment by meleu** [comment]
Real crash. I'm on the road now, but after a couple of hours I'll be able to give you some logs.

**Comment by meleu** [comment]
@leiradel I've just updated RetroArch, and the cores snes9x2010, snes9x2005 and bsnes.

All three cores crashes ("Segmentation fault" on Linux) right after getting the achievements for the game.
```txt
RetroArch [INFO] :: CHEEVOS testing SNES (8Mb padding).
RetroArch [INFO] :: CHEEVOS getting game id for hash 73afa2fc098f616c2047cd990283e6dc
RetroArch [INFO] :: CHEEVOS got game id 392.
RetroArch [INFO] :: CHEEVOS got achievements for game id 392.
Falha de segmentação
```

All three runs find when cheevos os OFF.

**Comment by leiradel** [comment]
Can you post a backtrack? Thanks!

**Comment by meleu** [comment]
Forgive my ignorance, I don't know what is a backtrack. :sweat:

**Comment by leiradel** [comment]
Argh, it was supposed to read "backtrace". Stupid corrector.

Compile RetroArch for debug:

    make clean && make -j 8 DEBUG=1

Run it with `gdb`:

    gdb retroarch
    (gdb) run

When it crashes, print a backtrace:

    bt

I'll try to reproduce on Windows too.

**Comment by leiradel** [comment]
It seems the JSON object with the achievements for this game is empty:

    $ curl -o adia.json "http://retroachievements.org/dorequest.php?r=patch&u=leiradel&g=392&f=3&l=1&t=XXXXXXXXXXXXXXXX"
    $ ls -l adia.json
    -rw-r--r-- 1 andre andre       0 Nov 23 19:39 adia.json

I'll fix RetroArch to log an error instead of crashing. @meleu could you report this problem to Retro Achievements?

**Comment by leiradel** [comment]
Fixed here: https://github.com/libretro/RetroArch/pull/4059

**Comment by meleu** [comment]
I don't know where to report it on RetroAchievements.org

The [Bug Reports in SNES section](http://retroachievements.org/viewforum.php?f=14) seems to be used for reporting bugs on RASnes (according to the description). But I [reported it there](http://retroachievements.org/viewtopic.php?t=3910).

@leiradel , can you see if it needs more details?

**Comment by leiradel** [comment]
I've added more details so that people can repro the problem. I think we did all we could, so I believe this issue can be closed.

**Comment by meleu** [comment]
I've tried to make this issue reach Scott here:
http://retroachievements.org/viewtopic.php?t=3803&o=15

Closing the issue here.

**Comment by leiradel** [comment]
Nice, maybe he clears up those doubts as well.
